// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/authz/authz.proto

package authz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision int32

const (
	Decision_DENY  Decision = 0
	Decision_ALLOW Decision = 1
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DENY",
		1: "ALLOW",
	}
	Decision_value = map[string]int32{
		"DENY":  0,
		"ALLOW": 1,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_authz_authz_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_proto_authz_authz_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_proto_authz_authz_proto_rawDescGZIP(), []int{0}
}

// Faithful representation of the authorization-relevant parts of http.Request.
// Headers use repeated Header (not map) because HTTP headers are multi-valued.
type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                     // r.Method
	Scheme        string                 `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`                                     // r.URL.Scheme
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`                                         // r.Host
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                         // r.URL.Path
	RawQuery      string                 `protobuf:"bytes,5,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`                 // r.URL.RawQuery
	Headers       []*Header              `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`                                   // r.Header (multi-value safe)
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`                                         // buffered r.Body
	ContentLength int64                  `protobuf:"varint,8,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"` // r.ContentLength
	RemoteAddr    string                 `protobuf:"bytes,9,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`           // r.RemoteAddr (ip:port)
	RequestId     string                 `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`             // PDAG-assigned
	Principal     string                 `protobuf:"bytes,11,opt,name=principal,proto3" json:"principal,omitempty"`                              // resolved from authn step
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proto_authz_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authz_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proto_authz_authz_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HttpRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *HttpRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_authz_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authz_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_authz_authz_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Decision               `protobuf:"varint,1,opt,name=decision,proto3,enum=pdag.authz.Decision" json:"decision,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // human-readable, included in audit log
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_authz_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authz_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_authz_authz_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DENY
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_authz_authz_proto protoreflect.FileDescriptor

const file_proto_authz_authz_proto_rawDesc = "" +
	"\n" +
	"\x17proto/authz/authz.proto\x12\n" +
	"pdag.authz\"\xc9\x02\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x05 \x01(\tR\brawQuery\x12,\n" +
	"\aheaders\x18\x06 \x03(\v2\x12.pdag.authz.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12%\n" +
	"\x0econtent_length\x18\b \x01(\x03R\rcontentLength\x12\x1f\n" +
	"\vremote_addr\x18\t \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x12\x1c\n" +
	"\tprincipal\x18\v \x01(\tR\tprincipal\"2\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"]\n" +
	"\x11AuthorizeResponse\x120\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x14.pdag.authz.DecisionR\bdecision\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*\x1f\n" +
	"\bDecision\x12\b\n" +
	"\x04DENY\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x012Q\n" +
	"\n" +
	"Authorizer\x12C\n" +
	"\tAuthorize\x12\x17.pdag.authz.HttpRequest\x1a\x1d.pdag.authz.AuthorizeResponseB)Z'github.com/FlorianMai1/pdag/proto/authzb\x06proto3"

var (
	file_proto_authz_authz_proto_rawDescOnce sync.Once
	file_proto_authz_authz_proto_rawDescData []byte
)

func file_proto_authz_authz_proto_rawDescGZIP() []byte {
	file_proto_authz_authz_proto_rawDescOnce.Do(func() {
		file_proto_authz_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authz_authz_proto_rawDesc), len(file_proto_authz_authz_proto_rawDesc)))
	})
	return file_proto_authz_authz_proto_rawDescData
}

var file_proto_authz_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_authz_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_authz_authz_proto_goTypes = []any{
	(Decision)(0),             // 0: pdag.authz.Decision
	(*HttpRequest)(nil),       // 1: pdag.authz.HttpRequest
	(*Header)(nil),            // 2: pdag.authz.Header
	(*AuthorizeResponse)(nil), // 3: pdag.authz.AuthorizeResponse
}
var file_proto_authz_authz_proto_depIdxs = []int32{
	2, // 0: pdag.authz.HttpRequest.headers:type_name -> pdag.authz.Header
	0, // 1: pdag.authz.AuthorizeResponse.decision:type_name -> pdag.authz.Decision
	1, // 2: pdag.authz.Authorizer.Authorize:input_type -> pdag.authz.HttpRequest
	3, // 3: pdag.authz.Authorizer.Authorize:output_type -> pdag.authz.AuthorizeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_authz_authz_proto_init() }
func file_proto_authz_authz_proto_init() {
	if File_proto_authz_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authz_authz_proto_rawDesc), len(file_proto_authz_authz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authz_authz_proto_goTypes,
		DependencyIndexes: file_proto_authz_authz_proto_depIdxs,
		EnumInfos:         file_proto_authz_authz_proto_enumTypes,
		MessageInfos:      file_proto_authz_authz_proto_msgTypes,
	}.Build()
	File_proto_authz_authz_proto = out.File
	file_proto_authz_authz_proto_goTypes = nil
	file_proto_authz_authz_proto_depIdxs = nil
}
